name:   'Tutorial for Reproducable Research Project Template'
url:    'http://mindymallory.github.io/'
author: 'Mindy Mallory'

gems: [jekyll-paginate]

include:  ['_pages']
baseurl: '/research-project-template'   

paginate:      10
paginate_path: '/blog/page:num/'
permalink:     '/blog/:year/:title/'

excerpt_separator: "{{ more }}"

markdown: 'kramdown'
timezone: 'America/Chicago'
highlighter: 'rouge'
