# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

permalink: pretty

# Setup
title:               Reproducible Research Project Template
tagline:             'Tutorial'
description:         'A template for starting a reproducible research project with R and RStudio'
url:                 http://mindymallory.github.io
baseurl:             'http://mindymallory.github.io/research-project-template/'
paginate:            5

# About/contact
author:
  name:              Mindy L. Mallory
  url:               http://mindymallory.github.io
  email:             mallorym@illinois.edu

# Custom vars
version:             
